version:  '3.8'
services:
  mysql:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: klaxoon

  php:
    image: klaxoon-api:dev
    depends_on:
      - "mysql"
    volumes:
      - './:/var/www'
    env_file:
      - .env
    user: $ID_USER:$ID_GROUP

  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - "mysql"
      - "php"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
