healthcheck:
    path: /healthcheck
    controller: App\Infrastructure\HealthCheck\HealthCheckController

list-bookmarks:
    path: /bookmarks
    controller: App\Infrastructure\Bookmark\BookmarkController::list
    methods: GET

add-bookmark:
    path: /bookmarks
    controller: App\Infrastructure\Bookmark\BookmarkController::add
    methods: PUT

delete-bookmark:
    path: /bookmarks/{id}
    controller: App\Infrastructure\Bookmark\BookmarkController::delete
    methods: DELETE
    requirements:
        id: '\d+'

edit-bookmark:
    path: /bookmarks/{id}
    controller: App\Infrastructure\Bookmark\BookmarkController::edit
    methods: POST
    requirements:
        id: '\d+'
